#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

set -x

# Script to install the various tools required


readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"
readonly third_party_dir="${repo_dir}/third_party"

readonly node_dir="${third_party_dir}/nodejs"
readonly node_version=16.16.0
readonly node_dl_addr="https://nodejs.org/dist/v${node_version}/node-v${node_version}-linux-x64.tar.xz"
readonly node_bin_dir="${node_dir}/bin"
readonly node_bin_path="${node_bin_dir}/node"
readonly npm_bin_path="${node_bin_dir}/npm"

readonly mongo_dir="${third_party_dir}/mongodb"
readonly mongo_dl_addr="https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.0.tgz"
readonly mongo_bin_path="${mongo_dir}/bin/mongod"
readonly mongo_sh_dl_addr="https://downloads.mongodb.com/compass/mongosh-1.5.4-linux-x64.tgz"

if [[ ${SKIP_SAFETY_CHECKS:-0} -ne 1 ]]; then
    function skip_safety_checks_message() {
        echo "If you want to skip safety checks and proceed anyway add SKIP_SAFETY_CHECKS=1 before the command" 1>&2
    }

    if [[ $EUID -eq 0 ]]; then
       echo "This script should not be run as root" 1>&2
       skip_safety_checks_message
       exit 1
    fi

    # Drop cached creds if there are any
    sudo -k

    # Try and sudo without password
    if sudo -n whoami &>/dev/null; then
        echo "Passwordless sudo is enabled. Running random installation scripts not recommended..." 1>&2
        skip_safety_checks_message
        exit 1
    fi
fi

install_dep() {
    local rc=`(eval $2 >/dev/null 2>&1); echo $?`
    if [[ $rc -ne 0 ]]; then
        echo "Installing $1"
        eval $3
    fi
}

mkdir -p third_party

install_dep \
    "node" \
    "test -s ${node_bin_path} && ${node_bin_path} --version | grep -q ${node_version}" \
    "\
    rm -rf ${node_dir}; \
    mkdir -p ${node_dir}; \
    cd ${node_dir}; \
    wget -q -O nodejs.tar.xz ${node_dl_addr}; \
    tar --strip-components=1 -xf nodejs.tar.xz; \
    rm nodejs.tar.xz; \
    "

install_dep \
    "mongo" \
    "test -s ${mongo_bin_path}" \
    "\
    rm -rf ${mongo_dir}; \
    mkdir -p ${mongo_dir}; \
    cd ${mongo_dir}; \
    wget -q -O mongojs.tgz ${mongo_dl_addr}; \
    wget -q -O mongosh.tgz ${mongo_sh_dl_addr}; \
    tar --strip-components=1 -xf mongojs.tgz; \
    tar --strip-components=1 -xf mongosh.tgz; \
    rm mongojs.tgz; \
    rm mongosh.tgz; \
    "

# Install the npm packages
cd ${repo_dir}
PATH="$node_bin_dir:$PATH" ${npm_bin_path} install

# Check for required system libs
(ldconfig -p | grep -q libcrypto.so.1.1) || echo "libcrypto.so.1.1 is missing. Mongo won't work without it. Package is likely openssl-1.1"; exit 1;

