#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Script to rebase the current branch onto the deploy branch


readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"
cd $repo_dir

readonly original_branch=`git rev-parse --abbrev-ref HEAD`;
git checkout deploy
git rebase "$original_branch"
git push
git checkout "$original_branch"
