#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

set -x

readonly collections=(\
    activitylogs \
    logchannels \
    guilds \
    rolesets \
);
readonly out_dir="prod_dump"

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )";
readonly dump_dir="${repo_dir}/${out_dir}"
readonly third_party_dir="${repo_dir}/third_party";
readonly mongoexport="${third_party_dir}/mongodb/tools/bin/mongoexport";

test -z "${out_dir// }" && (echo out_dir cannot be empty >&2; exit 1)

cd "$repo_dir"

source ./.prod_env

rm -rf "${dump_dir}"
mkdir -p "${dump_dir}"

for c in ${collections[@]}; do
  echo "Backing up collection: \"$c\""
  ${mongoexport} \
    --pretty \
    --jsonArray \
    --type json \
    --out "${dump_dir}/${c}.json" \
    --collection "$c" \
    "${MONGO_DB_URI}"

done


