#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# set -x


readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )";
cd $repo_dir;

rm -f gagbot.sqlite
rm -f gagbot.sqlite-shm
rm -f gagbot.sqlite-wal
zstd --decompress gagbot.sqlite.zst