#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

readonly bin="${bin:-migrate_mongo}"
readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"

cd "$repo_dir"

RUST_LOG=debug,gagbot_rs=debug,$bin=debug,serenity=debug \
    cargo run --bin $bin
