#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail


readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"
readonly third_party_dir="${repo_dir}/third_party"

readonly node_dir="${third_party_dir}/nodejs"
readonly node_bin_path="${node_dir}/bin/node"

cd "$repo_dir"
./run_mongo &

# Get the discord token from .env
source ./.env

$node_bin_path src/bot.js
