#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# set -x

readonly bin="${bin:-role_chihuahua}"
readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"

cd "$repo_dir"

cargo watch \
    -i '*.sqlite*' \
    -i '*.log*' \
    -x "run --bin $bin -- $*"
