#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# set -x

readonly bin="${bin:-role_chihuahua}"
readonly level=debug

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"
readonly third_party_dir="${repo_dir}/third_party"

readonly node_dir="${third_party_dir}/nodejs"
readonly node_bin_path="${node_dir}/bin/node"

cd "$repo_dir"
(cd ..; ./run_mongo &)

RUST_LOG=gagbot_rs=$level,$bin=$level,serenity=info,poise=info \
    cargo watch \
        -i '*.sqlite*' \
        -i '*.log*' \
        -x "run --bin $bin -- $*"
#RUST_LOG=debug cargo watch -x run
